require.config({
    baseUrl:'js/other',
    paths:{
        'jquery':'https://cdn.staticfile.org/jquery/2.0.0/jquery.min',
        'ko':'../lib/knockout-3.5.1'
    },
    shim:{
        un:{
            deps:[],
            exports:'obj'//与暴露出全局变量的名称一致
        }
    }
})

require(['jquery','say','un','ko'],function($,say,u,ko){
    ko.applyBindings({
        'koName':"knockoutjs"
    });
    console.log(u==null);
    console.log(u.unName);
    console.log($.name);
})